export interface Enemy {
    id: number;
    name: string;
    pictureUrl: string;
    thumbnailUrl: string;
    descriptionLong: string;
    descriptionShort: string;
    hp: number;
    fastAttack: number;
    strongAttack: number;
    specialAttack: number;
    fastDefense: number;
    strongDefense: number;
    specialDefense: number;
    fastAttAbility: string;
    strongAttAbility: string;
    specialAttAbility: string;
    fastDefAbility: string;
    strongDefAbility: string;
    specialDefAbility: string;
    fastAttAbilityIcon: string;
    strongAttAbilityIcon: string;
    specialAttAbilityIcon: string;
    fastDefAbilityIcon: string;
    strongDefAbilityIcon: string;
    specialDefAbilityIcon: string;
    isBoss: boolean;
    dungeonId: number;
}